"""initial_schema

Revision ID: d4bd663d7460
Revises: 
Create Date: 2026-07-22 08:20:23.604814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4bd663d7460'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('national_id', sa.String(length=20), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'PREFER_NOT_TO_SAY', name='gender'), nullable=True),
    sa.Column('contact_number', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patients_national_id'), 'patients', ['national_id'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('NURSE', 'DOCTOR', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('license_number', sa.String(length=50), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('auths',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auths_email'), 'auths', ['email'], unique=True)
    op.create_index(op.f('ix_auths_user_id'), 'auths', ['user_id'], unique=True)
    op.create_index(op.f('ix_auths_username'), 'auths', ['username'], unique=True)
    op.create_table('medical_encounters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('nurse_id', sa.UUID(), nullable=False),
    sa.Column('doctor_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('TRIAGE_IN_PROGRESS', 'AWAITING_REVIEW', 'COMPLETED', name='encounterstatus'), nullable=False),
    sa.Column('is_urgent', sa.Boolean(), nullable=False),
    sa.Column('chief_complaint', sa.String(length=500), nullable=True),
    sa.Column('encounter_timestamp', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['nurse_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medical_encounters_doctor_id'), 'medical_encounters', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_medical_encounters_nurse_id'), 'medical_encounters', ['nurse_id'], unique=False)
    op.create_index(op.f('ix_medical_encounters_patient_id'), 'medical_encounters', ['patient_id'], unique=False)
    op.create_table('clinical_notes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('encounter_id', sa.UUID(), nullable=False),
    sa.Column('subjective', sa.Text(), nullable=True),
    sa.Column('objective', sa.Text(), nullable=True),
    sa.Column('assessment', sa.Text(), nullable=True),
    sa.Column('plan', sa.Text(), nullable=True),
    sa.Column('is_finalized', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['encounter_id'], ['medical_encounters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clinical_notes_encounter_id'), 'clinical_notes', ['encounter_id'], unique=True)
    op.create_table('consultation_rooms',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('encounter_id', sa.UUID(), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'CLOSED', name='roomstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['encounter_id'], ['medical_encounters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consultation_rooms_encounter_id'), 'consultation_rooms', ['encounter_id'], unique=False)
    op.create_table('triage_interactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('encounter_id', sa.UUID(), nullable=False),
    sa.Column('sender_type', sa.Enum('AI', 'PATIENT', 'NURSE', name='sendertype'), nullable=False),
    sa.Column('message_content', sa.Text(), nullable=False),
    sa.Column('audio_url', sa.String(length=500), nullable=True),
    sa.Column('transcription_confidence', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['encounter_id'], ['medical_encounters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_triage_interactions_encounter_id'), 'triage_interactions', ['encounter_id'], unique=False)
    op.create_table('consultation_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('room_id', sa.UUID(), nullable=False),
    sa.Column('sender_id', sa.UUID(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('message_type', sa.Enum('TEXT', 'SYSTEM', 'ATTACHMENT', name='messagetype'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['consultation_rooms.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consultation_messages_room_id'), 'consultation_messages', ['room_id'], unique=False)
    op.create_index(op.f('ix_consultation_messages_sender_id'), 'consultation_messages', ['sender_id'], unique=False)
    op.create_table('room_memberships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('room_id', sa.UUID(), nullable=False),
    sa.Column('doctor_id', sa.UUID(), nullable=False),
    sa.Column('added_by_id', sa.UUID(), nullable=True),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['added_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['consultation_rooms.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('room_id', 'doctor_id', name='uq_room_doctor')
    )
    op.create_index(op.f('ix_room_memberships_doctor_id'), 'room_memberships', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_room_memberships_room_id'), 'room_memberships', ['room_id'], unique=False)
    op.create_table('consultation_attachments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('room_id', sa.UUID(), nullable=False),
    sa.Column('uploader_id', sa.UUID(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_filename', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['consultation_messages.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['consultation_rooms.id'], ),
    sa.ForeignKeyConstraint(['uploader_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consultation_attachments_message_id'), 'consultation_attachments', ['message_id'], unique=True)
    op.create_index(op.f('ix_consultation_attachments_room_id'), 'consultation_attachments', ['room_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_consultation_attachments_room_id'), table_name='consultation_attachments')
    op.drop_index(op.f('ix_consultation_attachments_message_id'), table_name='consultation_attachments')
    op.drop_table('consultation_attachments')
    op.drop_index(op.f('ix_room_memberships_room_id'), table_name='room_memberships')
    op.drop_index(op.f('ix_room_memberships_doctor_id'), table_name='room_memberships')
    op.drop_table('room_memberships')
    op.drop_index(op.f('ix_consultation_messages_sender_id'), table_name='consultation_messages')
    op.drop_index(op.f('ix_consultation_messages_room_id'), table_name='consultation_messages')
    op.drop_table('consultation_messages')
    op.drop_index(op.f('ix_triage_interactions_encounter_id'), table_name='triage_interactions')
    op.drop_table('triage_interactions')
    op.drop_index(op.f('ix_consultation_rooms_encounter_id'), table_name='consultation_rooms')
    op.drop_table('consultation_rooms')
    op.drop_index(op.f('ix_clinical_notes_encounter_id'), table_name='clinical_notes')
    op.drop_table('clinical_notes')
    op.drop_index(op.f('ix_medical_encounters_patient_id'), table_name='medical_encounters')
    op.drop_index(op.f('ix_medical_encounters_nurse_id'), table_name='medical_encounters')
    op.drop_index(op.f('ix_medical_encounters_doctor_id'), table_name='medical_encounters')
    op.drop_table('medical_encounters')
    op.drop_index(op.f('ix_auths_username'), table_name='auths')
    op.drop_index(op.f('ix_auths_user_id'), table_name='auths')
    op.drop_index(op.f('ix_auths_email'), table_name='auths')
    op.drop_table('auths')
    op.drop_table('users')
    op.drop_index(op.f('ix_patients_national_id'), table_name='patients')
    op.drop_table('patients')
    # ### end Alembic commands ###
